In [28]:
li : list[int] = [1,2,3,4,5,6,7,8,9]; # Normal List

print(li);

[1, 2, 3, 4, 5, 6, 7, 8, 9]


# **Pandas Series**

In [29]:
import pandas as pd;

s1 : pd.Series = pd.Series([1,2,3,4,5]); # Pandas Series

print(s1);

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [30]:
s1 : pd.Series = pd.Series((1,2,3,4,5));

print(s1);

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [31]:
s1 : pd.Series = pd.Series({
                            "a": 10,
                            "b": 20,
                            "c": 30,
                            "d": 40,
                            "e": 50,
                            "f": 60,
                            "g": 70,
                        }); # Pandas Series Apply In Tuple, Dict & List But Not Apply In Set

print(s1);

a    10
b    20
c    30
d    40
e    50
f    60
g    70
dtype: int64


In [32]:
values: list[int] = [1, 2, 3, 4, 5];

indexs: list[str] = ["a", "b", "c", "d", "e"];

s1: pd.Series = pd.Series(values, index=indexs);

print(s1);

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [33]:
values: list[int] = [1, 2, 3, 4, 5];

indexs: list[list[str]] = [
                        ["a1", "a1", "b1", "a1", "b1"], # Multi Index
                        ["a", "b", "c", "d", "e"]
                    ];

s1: pd.Series = pd.Series(values, index=indexs);

print(s1);

a1  a    1
    b    2
b1  c    3
a1  d    4
b1  e    5
dtype: int64


In [34]:
values: list[int] = [1, 2, 3, 4, 5];

indexs: list[list[str]] = [
                        ["a1", "a1", "a1", "b1", "b1"],
                        ["a", "b", "c", "d", "e"]
                    ];

s1: pd.Series = pd.Series(values, index=indexs , name="Pandas Series");

print(s1);

a1  a    1
    b    2
    c    3
b1  d    4
    e    5
Name: Pandas Series, dtype: int64


In [35]:
import numpy as np;

values: list[int] = [1, 2, 3, 4, 5];

indexs: list[list[str]] = [
                        ["a1", "a1", "a1", "b1", "b1"],
                        ["a", "b", "c", "d", "e"]
                    ];

s1: pd.Series = pd.Series(values,
                          index=indexs,
                          name="Pandas Series",
                          dtype=np.int32);

print(s1);

a1  a    1
    b    2
    c    3
b1  d    4
    e    5
Name: Pandas Series, dtype: int32


# **Pandas DataFrame**

In [36]:
s1 : pd.Series = pd.Series([1,2,3,4,5], name="ID");

s2 : pd.Series = pd.Series([10,20,30,40,50], name="Score");

s3 : pd.Series = pd.Series(["Suleman","Ahsan","Junaid","Ahmed","Abdullah"], name="Developer Name");

df : pd.DataFrame = pd.DataFrame({"ID": s1, "Score": s2, "Developer Name": s3}); # Pandas DataFrame

df

ID  Score Developer Name
0   1     10        Suleman
1   2     20          Ahsan
2   3     30         Junaid
3   4     40          Ahmed
4   5     50       Abdullah

In [37]:
s1 : pd.Series = pd.Series([1,2,3,4,5]);

s2 : pd.Series = pd.Series([10,20,30,40,50]);

s3 : pd.Series = pd.Series(["Suleman","Ahsan","Junaid","Ahmed","Abdullah"]);

df : pd.DataFrame = pd.DataFrame({"ID": s1, "Score": s2, "Developer Name": s3});

df

ID  Score Developer Name
0   1     10        Suleman
1   2     20          Ahsan
2   3     30         Junaid
3   4     40          Ahmed
4   5     50       Abdullah

In [38]:
s1 : pd.Series = pd.Series([1,2,3,4,5]);

s2 : pd.Series = pd.Series([10,20,30,40,50]);

s3 : pd.Series = pd.Series(["Suleman","Ahsan","Junaid","Ahmed","Abdullah"]);

df : pd.DataFrame = pd.DataFrame([s1, s2, s3]); # Top To Bottom

df

0      1       2      3         4
0        1      2       3      4         5
1       10     20      30     40        50
2  Suleman  Ahsan  Junaid  Ahmed  Abdullah

In [39]:
s1 : pd.Series = pd.Series([1,2,3,4,5], name="ID");

s2 : pd.Series = pd.Series([10,20,30,40,50], name="Score");

s3 : pd.Series = pd.Series(["Suleman","Ahsan","Junaid","Ahmed","Abdullah"], name="Developer Name");

df : pd.DataFrame = pd.DataFrame([s1, s2, s3]);

df

0      1       2      3         4
ID                    1      2       3      4         5
Score                10     20      30     40        50
Developer Name  Suleman  Ahsan  Junaid  Ahmed  Abdullah

In [40]:
s1 : pd.Series = pd.Series([1,2,3,4,5], name="ID");

s2 : pd.Series = pd.Series([10,20,30,40,50], name="Score");

s3 : pd.Series = pd.Series(["Suleman","Ahsan","Junaid","Ahmed","Abdullah"], name="Developer Name");

df : pd.DataFrame = pd.concat([s1, s2, s3], axis=1); # Left To Right

df

ID  Score Developer Name
0   1     10        Suleman
1   2     20          Ahsan
2   3     30         Junaid
3   4     40          Ahmed
4   5     50       Abdullah

In [41]:
data : list[list[int]] = [[1,2,3],
                          [4,5,6],
                          [7,8,9]];

df : pd.DataFrame = pd.DataFrame(data);

df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [42]:
data : list[list[int]] = [[1,2,3],
                          [4,5,6],
                          [7,8,9]];

df : pd.DataFrame = pd.DataFrame(data, columns=["A","B","C"]);

df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [43]:
data : list[list[int]] = [[1,2,3],
                          [4,5,6],
                          [7,8,9]];

df : pd.DataFrame = pd.DataFrame(data, columns=["A","B","C"], index=["X","Y","Z"]);

df

A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9

In [44]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [45]:
df.index

Index(['X', 'Y', 'Z'], dtype='object')

In [46]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
import numpy as np;

data = np.arange(10 * 10).reshape(10, 10);

print(data);

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [48]:
data = np.arange(10 * 10).reshape(10, 10);

df : pd.DataFrame = pd.DataFrame(data);

df

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [49]:
data = np.arange(10 * 10).reshape(10, 10);

df : pd.DataFrame = pd.DataFrame(data, columns=list("ABCDEFGHIJ"));

df

A   B   C   D   E   F   G   H   I   J
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [50]:
import pandas as pd;

dfl : list[pd.DataFrame] = pd.read_html("https://www.w3schools.com/python/python_operators.asp")

dfl

[  Operator            Name Example    Try it
 0        +        Addition   x + y  Try it »
 1        -     Subtraction   x - y  Try it »
 2        *  Multiplication   x * y  Try it »
 3        /        Division   x / y  Try it »
 4        %         Modulus   x % y  Try it »
 5       **  Exponentiation  x ** y  Try it »
 6       //  Floor division  x // y  Try it »,
    Operator        Example         Same As    Try it
 0         =          x = 5           x = 5  Try it »
 1        +=         x += 3       x = x + 3  Try it »
 2        -=         x -= 3       x = x - 3  Try it »
 3        *=         x *= 3       x = x * 3  Try it »
 4        /=         x /= 3       x = x / 3  Try it »
 5        %=         x %= 3       x = x % 3  Try it »
 6       //=        x //= 3      x = x // 3  Try it »
 7       **=        x **= 3      x = x ** 3  Try it »
 8        &=         x &= 3       x = x & 3  Try it »
 9        |=         x |= 3       x = x | 3  Try it »
 10       ^=         x ^= 3       x =

In [51]:
dfl[0] # Particular Table

Operator            Name Example    Try it
0        +        Addition   x + y  Try it »
1        -     Subtraction   x - y  Try it »
2        *  Multiplication   x * y  Try it »
3        /        Division   x / y  Try it »
4        %         Modulus   x % y  Try it »
5       **  Exponentiation  x ** y  Try it »
6       //  Floor division  x // y  Try it »

In [52]:
df : pd.DataFrame = pd.read_json("https://www.w3schools.com/python/pandas/data.js");

df # No Apply Particular Table Value In JSON

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [53]:
import pandas as pd;
import pandera as pa;

df = pd.DataFrame({
    "Column 1": [1, 4, 0, 10, 9],
    "Column 2": [-1.3, -1.4, -2.9, -10.1, -20.4],
    "Column 3": ["Value_1", "Value_2", "Value_3", "Value_2", "Value_1"]
});

schema = pa.DataFrameSchema(
    columns = {
            "Column 1": pa.Column(int, checks=pa.Check.le(10)), # Less Than Or Equal To
            "Column 2": pa.Column(float, checks=pa.Check.lt(-1.2)), # Less Than
            "Column 3": pa.Column(str, checks=[
                pa.Check.str_startswith("Value_"),
                pa.Check(lambda s: s.str.split("_", expand=True).shape[1] == 2)
            ])
        }
    );

validatedDf = schema(df);

validatedDf

Column 1  Column 2 Column 3
0         1      -1.3  Value_1
1         4      -1.4  Value_2
2         0      -2.9  Value_3
3        10     -10.1  Value_2
4         9     -20.4  Value_1

In [54]:
dir(pa.Check)

['__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slotnames__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_get_check_fn_code',
 'between',
 'eq',
 'equal_to',
 'equal_to',
 'from_builtin_check_name',
 'ge',
 'get_backend',
 'get_builtin_check_fn',
 'greater_than',
 'greater_than',
 'greater_than_or_equal_to',
 'greater_than_or_equal_to',
 'gt',
 'in_range',
 'in_range',
 'is_builtin_check',
 'isin',
 'isin',
 'le',
 'less_than',
 'less_than',
 'less_than_or_equal_to',
 'less_than_or_equal_to',
 'lt',
 'ne',
 'not_equal_to',
 'not_equal_to',
 'notin',
 'notin',
 'one_sample_ttest',
 'register_backend',
 'register_builtin_check_fn',
 'str_contains',
 'str_contains',
 'str_endswit

# **Pandas Slicing & Indexing**

In [55]:
s1 : pd.Series = pd.Series([1,2,3,4,5]);

display(s1);

display(s1[1]);

0    1
1    2
2    3
3    4
4    5
dtype: int64

np.int64(2)

In [56]:
s1 : pd.Series = pd.Series([1,2,3,4,5]);

display(s1);

print("Applying Slicing");

display(s1.iloc[1:4]); # Index Location Pass Only Numbers Same As Normal Slicing

0    1
1    2
2    3
3    4
4    5
dtype: int64

Applying Slicing


1    2
2    3
3    4
dtype: int64

In [57]:
display(s1[1:4]);

1    2
2    3
3    4
dtype: int64

In [58]:
s1 : pd.Series = pd.Series([1,2,3,4,5], index=["A", "B", "C", "D", "E"]);

display(s1);

print("Applying Slicing");

display(s1.iloc[1:4]);

A    1
B    2
C    3
D    4
E    5
dtype: int64

Applying Slicing


B    2
C    3
D    4
dtype: int64

In [59]:
s1 : pd.Series = pd.Series([1,2,3,4,5], index=["A", "B", "C", "D", "E"]);

display(s1);

print("Applying Slicing");

display(s1.loc["A":"D"]); # Index Location Pass Labels & Included End Value

A    1
B    2
C    3
D    4
E    5
dtype: int64

Applying Slicing


A    1
B    2
C    3
D    4
dtype: int64

In [60]:
s1 : pd.Series = pd.Series([1,2,3,4,5], index=["A", "B", "C", "D", "E"]);

display(s1);

print("Applying Indexing");

display(s1.iat[1]); # Index Location Pass Only Number Extract Only One Cell Value

A    1
B    2
C    3
D    4
E    5
dtype: int64

Applying Indexing


np.int64(2)

In [61]:
s1 : pd.Series = pd.Series([1,2,3,4,5], index=["A", "B", "C", "D", "E"]);

display(s1);

print("Applying Indexing");

display(s1.at["D"]); # Index Location Pass Label Extract Only One Cell Value

A    1
B    2
C    3
D    4
E    5
dtype: int64

Applying Indexing


np.int64(4)

In [62]:
chats: str = f"""
20:03:10 From Dr. Ghulam Shabbir to Everyone:
	AoA Honorable Sir Qasim Sb. Stay blessed always iA.
20:03:41 From M Qasim to Everyone:
	sir aj payare lag rahy hy
20:04:02 From Dr. Ghulam Shabbir to Everyone:
	Fantastic
20:04:06 From jhon wick to Qasim(CGAIO)(Direct Message):
	sir aj zia khan sir ne nahi ana
20:04:37 From jhon wick to Everyone:
	Reacted to "sir aj payare lag ra..." with 😂
20:04:44 From M Qasim to Everyone:
	Reacted to "sir aj payare lag ra..." with 😂
20:04:54 From M Qasim to Everyone:
	Removed a 😂 reaction from "sir aj payare lag ra..."
20:04:56 From M Qasim to Everyone:
	Reacted to "sir aj payare lag ra..." with 😂
20:04:57 From M Qasim to Everyone:
	Removed a 😂 reaction from "sir aj payare lag ra..."
20:06:04 From Abdullah to Everyone:
	sir ap kal ki class me ni ayen gy kia??
20:06:04 From M Qasim to Everyone:
	Sir Faisalabad b a rahy hy kya ap?
20:06:49 From Yasir to Everyone:
	Sir generative ai ki class online b hogi na?????
20:07:17 From Sheikh Hamza to Everyone:
	Sir data analytics ke liye maths statistics and probability ani chaye??
20:07:24 From Yasir to Everyone:
	Replying to "Sir generative ai ki..."

	@Ikhlas Bhojani PLease ask from sir?
20:07:57 From Ikhlas Bhojani to Everyone:
	Replying to "Sir generative ai ki..."

	ok wait
20:08:52 From Dr. Ghulam Shabbir to Everyone:
	Sir Qasim Sb. You were frequently discussed and were given honored and salute in our today's class at Islamabad. Dr. Ghulam Shabbir
20:09:12 From STONE to Everyone:
	Reacted to "Sir Qasim Sb. You we..." with 👍
20:09:15 From Hatif Humayun to Everyone:
	Reacted to "Sir Qasim Sb. You we..." with 👍
20:09:19 From Dr. Ghulam Shabbir to Everyone:
	Reacted to "Sir Qasim Sb. You we..." with 👍
20:09:27 From STONE to Everyone:
	Removed a 👍 reaction from "Sir Qasim Sb. You we..."
20:09:33 From STONE to Everyone:
	Reacted to "Sir Qasim Sb. You we..." with 👍
20:09:34 From STONE to Everyone:
	Removed a 👍 reaction from "Sir Qasim Sb. You we..."
20:12:02 From Amanat Wattoo to Everyone:
	Pd kia convention h
20:12:20 From Amanat Wattoo to Everyone:
	Ya koi or be naam de skte hn
20:12:33 From farhan to Everyone:
	Convention hey
20:12:50 From KifayatUllah to Everyone:
	screen is not visible to me, may be network issue or something else
20:14:16 From Rehan Alı WAKKAS to Everyone:
	Import pandas as pd and import pandora as pa.
	What is pd and pa ?
20:14:28 From farhan to Everyone:
	Just names
20:15:06 From Ikhlas Bhojani to Everyone:
	koi question ho tw hand raise kriyea jese i moka milega me unmute krdonga
20:15:41 From Talha to Everyone:
	Replying to "Import pandas as pd ..."

	Alias, instead of writing long words pandas and pandora, we can write pd and pa as their short form
20:15:45 From Rehan Alı WAKKAS to Everyone:
	@Ikhlas Bhojani
	Import pandas as pd and import pandora as pa.
	What is pd and pa ?
20:16:25 From Ikhlas Bhojani to Everyone:
	Replying to "@Ikhlas Bhojani
	Im..."

	alias
20:16:43 From Jazil Hashmi to Everyone:
	Import pandas could not be resolved from source. Why is this error coming? @Ikhlas Bhojani
20:16:55 From Ikhlas Bhojani to Everyone:
	Replying to "@Ikhlas Bhojani
	Im..."

	like nick name
20:17:36 From Ikhlas Bhojani to Everyone:
	!pip install pandas
20:17:46 From Rehan Alı WAKKAS to Everyone:
	Replying to "@Ikhlas Bhojani
	Im..."

	Do they refer to Directories or what ?
20:19:58 From Abdullah to Everyone:
	Pandas is usually imported under the pd alias. alias: In Python alias are an alternate name for referring to the same thing. Create an alias with the as keyword while importing: import pandas as pd. Now the Pandas package can be referred to as pd instead of pandas .
20:20:30 From farhan to Everyone:
	These are nicknames used by community
20:25:02 From ahsan rasheed to Everyone:
	Mary kush lectures rah gy hain
20:25:15 From ahsan rasheed to Everyone:
	Kia ya lecture record ho rhy hain
20:25:23 From ABDUL KHALIQ to Everyone:
	g
20:25:26 From ABDUL KHALIQ to Everyone:
	youtube
20:25:31 From ABDUL KHALIQ to Everyone:
	panaverse dao
20:25:48 From ahsan rasheed to Everyone:
	Thanks
20:26:30 From Kamran Ahmed to Everyone:
	tabular form in panada
20:26:46 From Sarwar Faridi to Everyone:
	TABULAR
20:26:54 From Sarwar Faridi to Everyone:
	2D
20:26:57 From Kamran Ahmed to Everyone:
	index value also shown
20:27:06 From Ahmed Siddiqui to Everyone:
	matrix
20:27:07 From Kamal Hassan to Everyone:
	series men indexing h or tabular form mn h
20:29:56 From Kaleem to Everyone:
	sir series ma duplicate values bhi dy kar daikhain!!
20:35:09 From Zeeshan Abbas to Everyone:
	Sir what is INT64
20:37:19 From Ikhlas Bhojani to Everyone:
	koi question he tw hand raise krke rakhen
20:37:51 From Zeeshan Abbas to Everyone:
	mera question hai what is INT64
20:38:04 From Abdullah to Everyone:
	smj e ni aya
	repeat krwa dyen
20:39:23 From Altaf Hussain to Everyone:
	Just like Chart of accounts in Accounting...
20:39:44 From Ahmed Siddiqui to Everyone:
	Reacted to "Just like Chart of a..." with 👍
20:40:40 From hi to Everyone:
	what is int 64
20:40:45 From hi to Everyone:
	dtype: int 64
20:40:54 From Zeeshan Abbas to Everyone:
	Sir why is showing INT64 in below
20:40:58 From Ikhlas Bhojani to Everyone:
	Replying to "mera question hai wh..."

	type hoti he data ki
20:42:24 From Kaleem to Everyone:
	in our structure data types of data we use key, value /key, pair values to define our data, how to translate that data Series?
20:42:27 From Asif Ali Shaikh to Everyone:
	int 64 is memory
20:42:44 From Asif Ali Shaikh to Everyone:
	Web3
20:45:11 From Zeeshan Abbas to Everyone:
	Reacted to "Web3" with 👍
20:46:15 From Galaxy to Everyone:
	Sir g account udaar dy dy
20:46:25 From Galaxy to Everyone:
	Reacted to Sir g account udaar ... with "😂"
20:46:40 From Ayesha Arshad to Everyone:
	Reacted to "Sir g account udaar ..." with 😂
20:46:40 From Ayesha Arshad to Everyone:
	Removed a 😂 reaction from "Sir g account udaar ..."
20:46:41 From jhon wick to Everyone:
	Reacted to "Sir g account udaar ..." with 😂
20:46:43 From Ayesha Arshad to Everyone:
	Reacted to "Sir g account udaar ..." with 😂
20:46:54 From Taif Ullah to Everyone:
	is bing equal to gpt 4
20:49:29 From fahad rasheed to Everyone:
	2 dimension data hy pora select krna parhyga "" mn
20:49:29 From Azfar Suhail to Everyone:
	from nptyping import DataFrame as DF, Structure as S

	s2 : DF[S["Abc : str"]] = pd.Series(['a','b','c','d','e'])
	s2
20:49:29 From Azfar Suhail to Everyone:
	this is working
20:51:57 From Saboor Hussain to Everyone:
	Reacted to "Sir g account udaa..." with 😂
20:51:59 From Saboor Hussain to Everyone:
	Removed a 😂 from "Sir g account udaa..."
20:58:40 From jhon wick to Everyone:
	yes
20:59:04 From farhan to Everyone:
	Kindly unmute
20:59:22 From Ikhlas Bhojani to Everyone:
	Replying to "Kindly unmute"

	wait
21:00:43 From PIAIC80919 Muhammad Asad to Everyone:
	Assalamu Aliakum
21:01:33 From Faizan Hassan to Everyone:
	s1.name kar k kar saktay hon ge
21:01:43 From PIAIC80919 Muhammad Asad to Everyone:
	I joined late on zoom meet so kindly share links that sir share until now
21:02:26 From Taif Ullah to Everyone:
	Replying to "I joined late on zoo..."

	every thing will be on github
21:04:19 From PIAIC80919 Muhammad Asad to Everyone:
	Numpy aur Pandas kay liya sir nay koi book share ki hai kay nahi
21:04:42 From Amanat Wattoo to Everyone:
	Replying to "Numpy aur Pandas kay..."

	no
21:05:21 From PIAIC80919 Muhammad Asad to Everyone:
	aur python kay liya koi alag WhatsApp group hai to please uska b link share kardien
21:06:00 From Amanat Wattoo to Everyone:
	Replying to "aur python kay liya ..."

	no koi group nhi bnia h
21:07:17 From Abdullah to Everyone:
	upper array wala code knsa ha??
21:07:51 From Hamza to Everyone:
	"Shape", "Shape"
21:08:10 From Hamza to Everyone:
	"Size", "Size"
21:08:26 From SheikhMAqib to Everyone:
	Double coat
21:08:33 From Azfar Suhail to Everyone:
	Shape turtle se import kara hai
21:08:51 From Azfar Suhail to Everyone:
	shape nptyping se import nhi howa
21:09:34 From Muhammad Uzair to Everyone:
	shape galat import ha
21:09:35 From Khadija Zahid to Everyone:
	shape ko kindly ek br explain kr den dbra
21:09:38 From PIAIC80919 Muhammad Asad to Qasim(CGAIO)(Direct Message):
	Assalamu Aliakum Sir Kindly sir mujhe bta dien k Data Science kay liya Math aur Statistic kay kon si books and courses hum karien
21:09:50 From Yasir to Everyone:
	shape import
21:09:53 From Yasir to Everyone:
	missing
21:09:56 From Muhammad Uzair to Everyone:
	from import typing shape
21:10:11 From Saboor Hussain to Everyone:
	sir
21:10:19 From Saboor Hussain to Everyone:
	aap nptyping se shape ko import karen
21:10:21 From Yasir to Everyone:
	import nhi kia shape
21:10:24 From farhan to Everyone:
	Shape import nahi thi
21:10:25 From Azfar Suhail to Everyone:
	turtle se import kara hai
21:14:10 From sadia to Everyone:
	can we get values 0 1 2 3 4 5 6 7 8 in vertical, abhi data horizontal arha hai
21:18:10 From Faiz M to Everyone:
	Sir chezy hard sy hard hoti ja rahe hy. aaj tho sir k oper oper ja raha hy.
21:18:56 From Qasim(CGAIO) to Everyone:
	https://www.w3schools.com/python/pandas/data.js
21:19:20 From Khadija Zahid to Everyone:
	html wala b ek br code dekha k bta de plz
21:19:22 From Abdullah to Everyone:
	kindly class k bd groups me sessions ka link send kr dia kryen
21:21:27 From Abdullah to Everyone:
	Replying to "kindly class k bd gr..."

	@Ikhlas Bhojani
21:22:11 From Ahmed Siddiqui to Everyone:
	what if data size in millions, what kind of preprocessing is required before handing over to pandas?
21:22:41 From Ikhlas Bhojani to Everyone:
	Replying to "kindly class k bd gr..."

	me ap logo ke group me nhi hn
21:22:59 From Abdullah to Everyone:
	Replying to "kindly class k bd gr..."

	bro sir sy kah dyen
	ya sir Imran sy request kr dyen
21:24:13 From Ikhlas Bhojani to Everyone:
	Replying to "html wala b ek br co..."

	pd.read_html("url")
21:26:02 From Kaleem to Everyone:
	how to make identical data ?
21:26:19 From Afifa Dar to Everyone:
	colmn3 k chexk me ==2 se kya horaha ?
21:29:40 From PIAIC80919 Muhammad Asad to Qasim(CGAIO)(Direct Message):
	sir assignment b day dein practice kay liya
21:32:29 From Ali Zar FSD to Everyone:
	sliding
21:32:41 From Ali Zar FSD to Everyone:
	likha gya sir
21:33:00 From fahad rasheed to Everyone:
	sir thora data large kryn plx
21:33:18 From fahad rasheed to Everyone:
	for slicing thora data bardhae
21:39:55 From raheela to Everyone:
	Name is tort ???
21:40:46 From Naveed Delattre to Everyone:
	it’s toad
21:41:45 From Altaf Hussain to Everyone:
	PIAIC-173738
21:41:51 From Hamza to Everyone:
	PIAIC-201785
21:41:52 From jhon wick to Everyone:
	piaic 223880
21:41:54 From Hina Zargham to Everyone:
	PIAIC101499
21:41:54 From Hatif Humayun to Everyone:
	PIAIC-52822
21:41:54 From Ahmed Siddiqui to Everyone:
	PIAIC123456
21:41:56 From Arif Najmi to Everyone:
	125657
21:42:00 From STONE to Everyone:
	ZAM - 786
21:42:01 From M. Waheed Iqbal (PIAIC_126369) to Everyone:
	PIAIC_126369
21:42:06 From ABDUL KHALIQ to Everyone:
	PIAIC-604031
21:42:11 From Arshad Siddiqui to Everyone:
	PIAIC120702
21:42:13 From Ali Zar FSD to Everyone:
	PIaic 223972
21:42:13 From Azfar Suhail to Everyone:
	PIAIC218333
21:42:14 From Kamran Ahmed to Everyone:
	PIAIC139495
21:42:18 From Ahmed to Everyone:
	216511
21:42:20 From Ayesha Arshad to Everyone:
	PIAIC-225620
21:42:25 From Kamal Hassan to Everyone:
	PIAIC58320
21:42:29 From Ahmed to Everyone:
	PIAIC-2165111
21:42:30 From Kaleem to Everyone:
	PIAIC:001100
""";

In [63]:
import re; # Regular Expression (RegEx)

patterns : str = r"""
(\d{2}:\d{2}:\d{2}) From (.*) to Everyone:
	(PIAIC-? ?\d{5,6})
""";

data : list[list[str]] = re.findall(patterns, chats);

data

[('21:41:45', 'Altaf Hussain', 'PIAIC-173738'),
 ('21:41:54', 'Hina Zargham', 'PIAIC101499'),
 ('21:41:54', 'Ahmed Siddiqui', 'PIAIC123456'),
 ('21:42:06', 'ABDUL KHALIQ', 'PIAIC-604031'),
 ('21:42:13', 'Azfar Suhail', 'PIAIC218333'),
 ('21:42:20', 'Ayesha Arshad', 'PIAIC-225620')]

In [64]:
df : pd.DataFrame = pd.DataFrame(data, columns=["Time", "Name","Roll Number"]);

df

Time            Name   Roll Number
0  21:41:45   Altaf Hussain  PIAIC-173738
1  21:41:54    Hina Zargham   PIAIC101499
2  21:41:54  Ahmed Siddiqui   PIAIC123456
3  21:42:06    ABDUL KHALIQ  PIAIC-604031
4  21:42:13    Azfar Suhail   PIAIC218333
5  21:42:20   Ayesha Arshad  PIAIC-225620