In [3]:
import pandas as pd;

li : list[int] = [1,2,3,4,5,6,7,8,9]; # Normal List

print(li);

[1, 2, 3, 4, 5, 6, 7, 8, 9]


# **Series**

In [4]:
s1 : pd.Series = pd.Series([1,2,3,4,5]); # Pandas Series

print(s1);

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [5]:
s1 : pd.Series = pd.Series((1,2,3,4,5));

print(s1);

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [6]:
s1 : pd.Series = pd.Series({
                            "a": 10,
                            "b":20,
                            "c":30,
                            "d":40,
                            "e":50,
                            "f":60,
                            "g":70,
                        }); # Series Apply In Tuple, Dict & List But Not Apply In Set

print(s1);

a    10
b    20
c    30
d    40
e    50
f    60
g    70
dtype: int64


In [7]:
values: list[int] = [1, 2, 3, 4, 5];

indexs: list[str] = ["a", "b", "c", "d", "e"];

s1: pd.Series = pd.Series(values, index=indexs);

print(s1);

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [8]:
values: list[int] = [1, 2, 3, 4, 5];

indexs: list[list[str]] = [
                        ["a1", "a1", "a1", "b1", "b1"], # Multi Index
                        ["a", "b", "c", "d", "e"]
                    ];

s1: pd.Series = pd.Series(values, index=indexs);

print(s1);

a1  a    1
    b    2
    c    3
b1  d    4
    e    5
dtype: int64


In [9]:
values: list[int] = [1, 2, 3, 4, 5];

indexs: list[list[str]] = [
                        ["a1", "a1", "a1", "b1", "b1"],
                        ["a", "b", "c", "d", "e"]
                    ];

s1: pd.Series = pd.Series(values, index=indexs , name="Pandas Series");

print(s1);

a1  a    1
    b    2
    c    3
b1  d    4
    e    5
Name: Pandas Series, dtype: int64


In [10]:
import numpy as np;

values: list[int] = [1, 2, 3, 4, 5];

indexs: list[list[str]] = [
                        ["a1", "a1", "a1", "b1", "b1"],
                        ["a", "b", "c", "d", "e"]
                    ];

s1: pd.Series = pd.Series(values,
                          index=indexs,
                          name="Pandas Series",
                          dtype=np.int32);

print(s1);

a1  a    1
    b    2
    c    3
b1  d    4
    e    5
Name: Pandas Series, dtype: int32


# **DataFrame**

In [11]:
s1 : pd.Series = pd.Series([1,2,3,4,5], name="ID");

s2 : pd.Series = pd.Series([10,20,30,40,50], name="Score");

s3 : pd.Series = pd.Series(["Suleman","Ahsan","Junaid","Ahmed","Abdullah"], name="Developer Name");

df : pd.DataFrame = pd.DataFrame({"ID": s1, "Score": s2, "Developer Name": s3}); # Pandas DataFrame

df

ID  Score Developer Name
0   1     10        Suleman
1   2     20          Ahsan
2   3     30         Junaid
3   4     40          Ahmed
4   5     50       Abdullah

In [12]:
s1 : pd.Series = pd.Series([1,2,3,4,5]);

s2 : pd.Series = pd.Series([10,20,30,40,50]);

s3 : pd.Series = pd.Series(["Suleman","Ahsan","Junaid","Ahmed","Abdullah"]);

df : pd.DataFrame = pd.DataFrame({"ID": s1, "Score": s2, "Developer Name": s3});

df

ID  Score Developer Name
0   1     10        Suleman
1   2     20          Ahsan
2   3     30         Junaid
3   4     40          Ahmed
4   5     50       Abdullah

In [13]:
s1 : pd.Series = pd.Series([1,2,3,4,5], name="ID");

s2 : pd.Series = pd.Series([10,20,30,40,50], name="Score");

s3 : pd.Series = pd.Series(["Suleman","Ahsan","Junaid","Ahmed","Abdullah"], name="Developer Name");

df : pd.DataFrame = pd.DataFrame([s1, s2, s3]);

df

0      1       2      3         4
ID                    1      2       3      4         5
Score                10     20      30     40        50
Developer Name  Suleman  Ahsan  Junaid  Ahmed  Abdullah

In [14]:
s1 : pd.Series = pd.Series([1,2,3,4,5], name="ID");

s2 : pd.Series = pd.Series([10,20,30,40,50], name="Score");

s3 : pd.Series = pd.Series(["Suleman","Ahsan","Junaid","Ahmed","Abdullah"], name="Developer Name");

df : pd.DataFrame = pd.concat([s1, s2, s3], axis=1);

df

ID  Score Developer Name
0   1     10        Suleman
1   2     20          Ahsan
2   3     30         Junaid
3   4     40          Ahmed
4   5     50       Abdullah

In [15]:
data : list[list[int]] = [[1,2,3],
                          [4,5,6],
                          [7,8,9]];

df : pd.DataFrame = pd.DataFrame(data);

df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [16]:
data : list[list[int]] = [[1,2,3],
                          [4,5,6],
                          [7,8,9]];

df : pd.DataFrame = pd.DataFrame(data, columns=["A","B","C"]);

df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [17]:
data : list[list[int]] = [[1,2,3],
                          [4,5,6],
                          [7,8,9]];

df : pd.DataFrame = pd.DataFrame(data, columns=["A","B","C"], index=["X","Y","Z"]);

df

A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9

In [18]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [19]:
df.index

Index(['X', 'Y', 'Z'], dtype='object')

In [20]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
from nptyping import NDArray, Shape, UInt64;

data : NDArray[Shape["10, 10"], UInt64] = np.arange(10 * 10).reshape(10, 10);

print(data);

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [22]:
from nptyping import NDArray, Shape, UInt64;

data : NDArray[Shape["10, 10"], UInt64] = np.arange(10 * 10).reshape(10, 10);

df : pd.DataFrame = pd.DataFrame(data);

df

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [23]:
from nptyping import NDArray, Shape, UInt64;

data : NDArray[Shape["10, 10"], UInt64] = np.arange(10 * 10).reshape(10, 10);

df : pd.DataFrame = pd.DataFrame(data, columns=list("ABCDEFGHIJ"));

df

A   B   C   D   E   F   G   H   I   J
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [31]:
import pandas as pd;

dfl : list[pd.DataFrame] = pd.read_html("https://www.w3schools.com/python/python_operators.asp")

dfl

[  Operator            Name Example    Try it
 0        +        Addition   x + y  Try it »
 1        -     Subtraction   x - y  Try it »
 2        *  Multiplication   x * y  Try it »
 3        /        Division   x / y  Try it »
 4        %         Modulus   x % y  Try it »
 5       **  Exponentiation  x ** y  Try it »
 6       //  Floor division  x // y  Try it »,
    Operator  Example     Same As    Try it
 0         =    x = 5       x = 5  Try it »
 1        +=   x += 3   x = x + 3  Try it »
 2        -=   x -= 3   x = x - 3  Try it »
 3        *=   x *= 3   x = x * 3  Try it »
 4        /=   x /= 3   x = x / 3  Try it »
 5        %=   x %= 3   x = x % 3  Try it »
 6       //=  x //= 3  x = x // 3  Try it »
 7       **=  x **= 3  x = x ** 3  Try it »
 8        &=   x &= 3   x = x & 3  Try it »
 9        |=   x |= 3   x = x | 3  Try it »
 10       ^=   x ^= 3   x = x ^ 3  Try it »
 11      >>=  x >>= 3  x = x >> 3  Try it »
 12      <<=  x <<= 3  x = x << 3  Try it »,
   Operator   

In [32]:
dfl[0] # Particular Table

Operator            Name Example    Try it
0        +        Addition   x + y  Try it »
1        -     Subtraction   x - y  Try it »
2        *  Multiplication   x * y  Try it »
3        /        Division   x / y  Try it »
4        %         Modulus   x % y  Try it »
5       **  Exponentiation  x ** y  Try it »
6       //  Floor division  x // y  Try it »

In [33]:
df : pd.DataFrame = pd.read_json("https://www.w3schools.com/python/pandas/data.js");

df

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]